---
- hosts: docker
  become: yes
  tasks:
    - name: Install pip
      apt: name=pip state=present

    - name: install docker-py
      pip: name=docker-py

    - name: Copy dockerfile
      copy:
        src: "{{ path }}/Dockerfile"
        dest: /home/ubuntu
    
    - name: Copy artifact
      copy:
        src: "{{ path }}/target"
        dest: /home/ubuntu

    - name: docker-login
      docker_login:
        registry: docker.io
        username: thirupranav
        password: dckr_pat_crL-4_RYwChzQLajNfsFGDKLiPs

    - name: remove Docker image
      docker_image:
        name: thirupranav/app
        state: absent

    - name: Build Docker image from Dockerfile
      docker_image:
        name: thirupranav/app
        source: build
        build:
          path: /home/ubuntu
        state: present
        push: yes
    
    - name: Remove container named app
      docker_container:
        name: app
        state: absent    
    
    - name: Run a container
      docker_container:
        image: thirupranav/app
        name: app
        state: started
        ports:
          - "8090:8080"
 
    - name: remove dockerfile
      file:
        path: /home/ubuntu/Dockerfile
        state: absent

    - name: remove artifacts
      file:
        path: /home/ubuntu/target
        state: absent
