---
- hosts: docker
  become: yes
  tasks:
    - name: Install pip
      apt: name=pip state=present



    - name: install docker-py
      pip: name=docker-py



    - name: Copy dockerfile
      copy:
        src: "{{ path }}/Dockerfile"
        dest: /home/ubuntu

    - name: docker-login
      shell: docker login

    - name: Build Docker image from Dockerfile
      docker_image:
        name: thirupranav/app
        source: build
        build:
          path: /home/ubuntu
        state: present
        push: yes

 
    - name: remove dockerfile
      file:
        path: /home/ubuntu/Dockerfile
        state: absent